destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/server-integrations-pdf"
port: 4010
output: pdf
product: android
print_title: HALO Server Integrations
print_subtitle: Version 2.2
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true