destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/cms-pdf"
port: 4010
output: pdf
product: cms
print_title: HALO CMS
print_subtitle: Version 2.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true